import assert from 'node:assert/strict';
export const metadata = { name:'shared-session-ui', profiles:['desktop','mobile'] };
export default async function({page,evidence,baseUrl,profile}) {
 const errors=[]; page.on('pageerror',error=>errors.push(error.message));
 await page.goto(baseUrl);
 await page.locator('.cwu-browser').waitFor();
 await evidence.chapter('共享 Session UI', {description:profile+' · 实际 Minimal Host 候选'});
 const create=page.getByRole('button',{name:'新建对话',exact:true});
 if(profile==='mobile' && await page.locator('.cwu-browser-list-toggle').getAttribute('aria-expanded')==='false') await page.locator('.cwu-browser-list-toggle').click();
 await create.click();
 const composer=page.locator('.cwu-composer textarea');
 await composer.waitFor();
 assert.equal(await page.locator('.cwu-browser-summary > span').count(),0);
 const togglePosition=()=>page.locator('.cwu-browser-list-toggle').evaluate(el=>{const rect=el.getBoundingClientRect();return {x:rect.x,y:rect.y};});
 const beforeToggle=await togglePosition();
 await page.locator('.cwu-browser-list-toggle').click();
 assert.deepEqual(await togglePosition(),beforeToggle);
 await page.locator('.cwu-browser-list-toggle').click();
 assert.deepEqual(await togglePosition(),beforeToggle);
 await evidence.checkpoint('默认最近列表与单行输入栏');
 const marker=profile+'-'+Date.now();
 const long='请检查附件预览 '+marker+'。\n\n'+Array.from({length:65},(_,i)=>`第 ${i+1} 段要求：检查布局和执行记录。`).join('\n\n');
 await composer.fill(long);
 await page.locator('.cwu-composer button[type=submit]').click();
 await page.getByText('正在检查附件预览和输入布局。',{exact:true}).waitFor();
 await page.locator('.cwu-process-command').getByText('node inspect.js',{exact:true}).waitFor();
 await evidence.checkpoint('最新消息下方公开执行过程');
 const message=page.locator('.cwu-message').last();
 assert.equal(await message.evaluate((el)=>Boolean(el.nextElementSibling?.classList.contains('cwu-technical'))),true);
 await page.getByText('已检查布局。',{exact:false}).first().waitFor({timeout:15000});
 await page.getByText('执行记录',{exact:true}).waitFor();
 await page.locator('.cwu-technical-toggle').click();
 await evidence.checkpoint('完成记录限高与最终回复完整展示');
 const user=page.locator('.cwu-message.is-user .cwu-scroll-content').first();
 if(await user.count()) assert.equal(await user.evaluate(el=>el.scrollHeight>el.clientHeight),true);
 await composer.fill('尚未发送的草稿');
 const toggle=page.locator('.cwu-browser-list-toggle');
 if(profile==='mobile') await toggle.click();
 await page.getByRole('button',{name:'新建对话',exact:true}).click();
 await page.locator('.cwu-session-header').getByRole('heading',{name:'新对话',exact:true}).waitFor();
 await composer.fill('另一个会话的草稿');
 if(profile==='mobile') await toggle.click();
 await page.locator('.cwu-browser-row-main').filter({hasText:marker}).first().click();
 await page.waitForFunction(()=>document.querySelector('.cwu-composer textarea')?.value==='尚未发送的草稿');
 assert.equal(await composer.inputValue(),'尚未发送的草稿');
 await toggle.click();
 await evidence.checkpoint('侧栏开关与会话草稿恢复');
 if(profile==='desktop') await toggle.click();
 if(profile==='mobile' && await toggle.getAttribute('aria-expanded')!=='true') await toggle.click();
 await page.getByRole('button',{name:'搜索与历史',exact:true}).click();
 await page.getByRole('searchbox',{name:'搜索标题或正文'}).fill('附件预览');
 await page.locator('.cwu-finder-results button').first().waitFor();
 await evidence.checkpoint('搜索标题正文与历史共用弹窗');
 await page.keyboard.press('Escape');
 await page.locator('.cwu-session-finder').waitFor({state:'hidden'});
 assert.deepEqual(errors,[]);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
}
